services:
  backend:
    environment:
      - NODE_ENV=test
      - MONGO_URI=mongodb://mongo-test:27017/rajhans-ecommerce-test?replicaSet=rs0
    command: ["npm", "run", "test:integration"]
    depends_on:
      mongo-test:
        condition: service_healthy
      redis:
        condition: service_healthy
