services:
  backend:
    image: rajhansteaprod/rajhans-tea-backend:latest
    pull_policy: always
    container_name: tea-backend
    env_file: .env
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - tea-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: rajhansteaprod/rajhans-tea-frontend:latest
    pull_policy: always
    container_name: tea-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - tea-network

  nginx:
    image: nginx:alpine
    container_name: tea-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs/self.crt:/etc/nginx/ssl/cert.crt
      - /etc/ssl/private/self.key:/etc/nginx/ssl/key.key
    depends_on:
      - frontend
      - backend
    networks:
      - tea-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: tea-redis
    restart: unless-stopped
    networks:
      - tea-network
    command: redis-server --requirepass ""
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis-data:/data

networks:
  tea-network:
    driver: bridge

volumes:
  redis-data:
