import { Router } from 'express';
import healthRoutes from './health.routes';
import authRoutes from '../../../modules/auth/auth.routes';
import adminRoutes from '../../../modules/admin/admin.routes';
import catalogRoutes from '../../../modules/catalog/catalog.routes';
import pricingRoutes from '../../../modules/pricing/pricing.routes';
import cartRoutes from '../../../modules/cart/cart.routes';
import paymentRoutes from '../../../modules/payments/payment.routes';
import inventoryRoutes from '../../../modules/inventory/inventory.routes';
import promotionsRoutes from '../../../modules/promotions/promotions.routes';
import promoRoutes from '../../../modules/promo/promo.routes';
import reviewsRoutes from '../../../modules/reviews/reviews.routes';
import auditRoutes from '../../../modules/audit/audit.routes';
import settingsRoutes from '../../../modules/settings/settings.routes';
import cmsRoutes from '../../../modules/cms/cms.routes';
import searchRoutes from '../../../modules/search/search.routes';
import newsletterRoutes from '../../../modules/newsletter/newsletter.routes';
import shipmentRoutes from '../../../modules/shipments/shipments.routes';
import contactRoutes from '../../../modules/contact/contact.routes';
const router = Router();

router.use(healthRoutes);
router.use(authRoutes);
router.use(adminRoutes);
router.use(catalogRoutes);
router.use(pricingRoutes);
router.use(cartRoutes);
router.use(paymentRoutes);
router.use(inventoryRoutes);
router.use(promotionsRoutes);
router.use(promoRoutes);
router.use(reviewsRoutes);
router.use(auditRoutes);
router.use(settingsRoutes);
router.use(cmsRoutes);
router.use(searchRoutes);
router.use(newsletterRoutes);
router.use(shipmentRoutes);
router.use(contactRoutes);
export default router;
